#!/usr/bin/perl

# Copyright (C) 2010 Modestas Vainius <modax@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

use strict;
use warnings;
use Debian::Debhelper::Dh_Lib;

init();

foreach my $pkg (@{$dh{DOPACKAGES}}) {
    my $arch = package_arch($pkg);
    next if $arch eq "all";

    my $infile = "debian/$pkg.symbols.in";
    my $outfile = "debian/$pkg.symbols.$arch";

    if ($0 =~ /_symbolfile$/) {
        if (-f $infile) {
            doit('pkgkde-symbolshelper', 'symbolfile', '-p', $pkg, '-o', $outfile);
        }
    } elsif ($0 =~ /_clean$/) {
        inhibit_log();
        if (-f $outfile) {
            doit("rm", "-f", $outfile);
        }
    } else {
        error("invalid program execution");
    }
}
