#!/usr/bin/perl

use strict;
use warnings;

use constant DATADIR => '/usr/share/pkg-kde-tools';

my $dir;
if ($0 =~ m@^(.+)/[^/]+$@) {
    $dir = $1;
    unless ($dir && -f "$dir/dpkg-gensymbols.pl" &&
        -f "$dir/Dpkg/Shlibs/SymbolFile.pm") {
        $dir = undef;
    }
}

unless ($dir) {
    $dir = DATADIR;
}

unshift @INC, $dir;
if (-f "$dir/dpkg-gensymbols.pl") {
    do "$dir/dpkg-gensymbols.pl";
} else {
    print STDERR "pkgkde-gensymbols: unable to determine execution context.", "\n";
    exit 1;
}
